# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - '*'
variables:
  githubPAT: "$(GithubPAT)" #GitHubPAT

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  persistCredentials: true    #Allow scripts to access the system token
  clean: true 

- task: Bash@3
  name: SyncRepo
  inputs:
    targetType: 'inline'
    script: |
      git config --global user.email "gingy@wicresoft.com"
      git config --global user.name "gingy"
      git add .
      git commit -m "test"
      git remote -v
      # git push -
      # git branch -r | grep -v '\->' | while read remote; do git branch --track "${remote#origin/}" "$remote"; done
      # git remote add https://github.com/gingyuan/TestSync.git
      # git branch -r | grep -v '\->' | while read remote; do git -c http.extraheader="AUTHORIZATION: bearer $(githubPAT)" push -u "${remote#origin/}"; done
